name: WAMP Dart

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.38.7

      - name: Cache Pub dependencies
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}-v2
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: make install

      - name: Verify formatting
        run: make check-format

      - name: Check lint
        run: make lint
